use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelInfo {
    pub id: String,
    pub name: String,
    pub description: String,
    pub size_bytes: u64,
    pub size_label: String,
    pub tag: String,
    pub hf_repo: String,
    pub hf_filename: String,
    pub tokenizer_repo: String,
    pub chat_template: ChatTemplate,
    pub company: String,
    pub parameters: String,
    pub quantization: String,
    pub best_for: Vec<String>,
    /// Maximum context window in tokens. Prompt + generated tokens must stay within this.
    pub context_length: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ChatTemplate {
    Llama3,
    SmolLM,
    Gemma,
    Phi3,
    Qwen,
}

pub fn get_catalog() -> Vec<ModelInfo> {
    vec![
        ModelInfo {
            id: "llama-3.2-1b".into(),
            name: "Llama 3.2 1B".into(),
            description: "Compact model great for quick tasks and chat. One of Meta's smallest instruction-tuned models, offering fast responses with reasonable quality for everyday conversations.".into(),
            size_bytes: 700_000_000,
            size_label: "~700 MB".into(),
            tag: "Tiny".into(),
            hf_repo: "bartowski/Llama-3.2-1B-Instruct-GGUF".into(),
            hf_filename: "Llama-3.2-1B-Instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "unsloth/Llama-3.2-1B-Instruct".into(),
            chat_template: ChatTemplate::Llama3,
            company: "Meta".into(),
            parameters: "1 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["Quick chat".into(), "Simple Q&A".into(), "Low-end devices".into()],
            context_length: 4096,
        },
        ModelInfo {
            id: "smollm2-1.7b".into(),
            name: "SmolLM2 1.7B".into(),
            description: "HuggingFace's own small language model, designed for efficiency. Punches above its weight with strong general knowledge and fast inference on mobile devices.".into(),
            size_bytes: 1_000_000_000,
            size_label: "~1.0 GB".into(),
            tag: "Popular".into(),
            hf_repo: "bartowski/SmolLM2-1.7B-Instruct-GGUF".into(),
            hf_filename: "SmolLM2-1.7B-Instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "HuggingFaceTB/SmolLM2-1.7B-Instruct".into(),
            chat_template: ChatTemplate::SmolLM,
            company: "HuggingFace".into(),
            parameters: "1.7 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["General chat".into(), "Summarization".into(), "Fast responses".into()],
            context_length: 4096,
        },
        ModelInfo {
            id: "gemma-2-2b".into(),
            name: "Gemma 2 2B".into(),
            description: "Google's lightweight model optimized specifically for on-device deployment. Excellent balance of quality and speed, built with mobile-first design.".into(),
            size_bytes: 1_500_000_000,
            size_label: "~1.5 GB".into(),
            tag: "Fast".into(),
            hf_repo: "bartowski/gemma-2-2b-it-GGUF".into(),
            hf_filename: "gemma-2-2b-it-Q4_K_M.gguf".into(),
            tokenizer_repo: "unsloth/gemma-2-2b-it".into(),
            chat_template: ChatTemplate::Gemma,
            company: "Google".into(),
            parameters: "2 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["On-device AI".into(), "General tasks".into(), "Balanced quality".into()],
            context_length: 8192,
        },
        ModelInfo {
            id: "llama-3.2-3b".into(),
            name: "Llama 3.2 3B".into(),
            description: "Meta's best small model for mobile. Strong reasoning, creative writing, and conversational ability. The recommended model for most users.".into(),
            size_bytes: 2_000_000_000,
            size_label: "~2.0 GB".into(),
            tag: "Popular".into(),
            hf_repo: "bartowski/Llama-3.2-3B-Instruct-GGUF".into(),
            hf_filename: "Llama-3.2-3B-Instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "unsloth/Llama-3.2-3B-Instruct".into(),
            chat_template: ChatTemplate::Llama3,
            company: "Meta".into(),
            parameters: "3 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["Chat & reasoning".into(), "Creative writing".into(), "Best overall".into()],
            context_length: 4096,
        },
        ModelInfo {
            id: "phi-3.5-mini".into(),
            name: "Phi-3.5 Mini".into(),
            description: "Microsoft's compact powerhouse, trained on high-quality data including code. Exceptional at programming tasks, debugging, and technical explanations.".into(),
            size_bytes: 2_200_000_000,
            size_label: "~2.2 GB".into(),
            tag: "Code".into(),
            hf_repo: "bartowski/Phi-3.5-mini-instruct-GGUF".into(),
            hf_filename: "Phi-3.5-mini-instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "microsoft/Phi-3.5-mini-instruct".into(),
            chat_template: ChatTemplate::Phi3,
            company: "Microsoft".into(),
            parameters: "3.8 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["Code generation".into(), "Debugging".into(), "Technical Q&A".into()],
            context_length: 4096,
        },
        ModelInfo {
            id: "qwen-2.5-0.5b".into(),
            name: "Qwen 2.5 0.5B".into(),
            description: "Alibaba's tiniest model. Lightning-fast responses on any device. Best for simple questions where speed matters more than depth.".into(),
            size_bytes: 400_000_000,
            size_label: "~380 MB".into(),
            tag: "Tiny".into(),
            hf_repo: "bartowski/Qwen2.5-0.5B-Instruct-GGUF".into(),
            hf_filename: "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "Qwen/Qwen2.5-0.5B-Instruct".into(),
            chat_template: ChatTemplate::Qwen,
            company: "Alibaba".into(),
            parameters: "0.5 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["Ultra-fast".into(), "Basic tasks".into(), "Any device".into()],
            context_length: 4096,
        },
        ModelInfo {
            id: "qwen-2.5-1.5b".into(),
            name: "Qwen 2.5 1.5B".into(),
            description: "Strong multilingual model from Alibaba. Supports Chinese, English, and many other languages. Good reasoning ability for its size.".into(),
            size_bytes: 990_000_000,
            size_label: "~940 MB".into(),
            tag: "Popular".into(),
            hf_repo: "bartowski/Qwen2.5-1.5B-Instruct-GGUF".into(),
            hf_filename: "Qwen2.5-1.5B-Instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "Qwen/Qwen2.5-1.5B-Instruct".into(),
            chat_template: ChatTemplate::Qwen,
            company: "Alibaba".into(),
            parameters: "1.5 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["Multilingual".into(), "Reasoning".into(), "Good balance".into()],
            context_length: 4096,
        },
        ModelInfo {
            id: "qwen-2.5-3b".into(),
            name: "Qwen 2.5 3B".into(),
            description: "The best Qwen model for mobile. Excellent reasoning, multilingual support, and strong performance across diverse tasks. Competes with larger models.".into(),
            size_bytes: 1_930_000_000,
            size_label: "~1.8 GB".into(),
            tag: "Popular".into(),
            hf_repo: "bartowski/Qwen2.5-3B-Instruct-GGUF".into(),
            hf_filename: "Qwen2.5-3B-Instruct-Q4_K_M.gguf".into(),
            tokenizer_repo: "Qwen/Qwen2.5-3B-Instruct".into(),
            chat_template: ChatTemplate::Qwen,
            company: "Alibaba".into(),
            parameters: "3 Billion".into(),
            quantization: "Q4_K_M (4-bit)".into(),
            best_for: vec!["Complex tasks".into(), "Multilingual".into(), "High quality".into()],
            context_length: 4096,
        },
    ]
}
